"""add-on-delete-cascade-in-chat-message

Revision ID: 2e74faa1dc71
Revises: 585662129743
Create Date: 2026-02-05 12:46:16.514570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e74faa1dc71'
down_revision: Union[str, Sequence[str], None] = '585662129743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_messages_ibfk_1'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_ibfk_1'), 'chat_messages', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
