name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Copy files to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/AgentOps"

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd ~/AgentOps/
            cat << EOF > .env
            ENV="production"
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
            MYSQL_USER=${{ secrets.MYSQL_USER }}
            MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
            MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
            EOF
            chmod 600 .env
            cat <<'EOF' > nginx.conf
            server {
              listen 80;
              server_name api.agentops.p-e.kr;
              return 301 https://$host$request_uri;
            }

            server {
              listen 443 ssl;
              server_name api.agentops.p-e.kr;

              ssl_certificate /etc/letsencrypt/live/api.agentops.p-e.kr/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/api.agentops.p-e.kr/privkey.pem;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;

              client_max_body_size 10m;

              location / {
                proxy_pass http://agent_service:8000;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
              }
            }
            EOF
            docker compose up mydb -d
            docker compose up agent_service -d --build --force-recreate
            docker compose up nginx -d --force-recreate
            docker container prune -f
            docker image prune -f
            docker buildx prune -f
            echo "Deployment completed successfully!"
